services:
  admin-api:
    container_name: admin-api
    restart: always
    networks:
      - external
    ports:
      - '4000:4000'
    env_file:
      - .env
      - .docker.env
    build:
      dockerfile: ./apps/admin-api/Dockerfile

networks:
  external:
    external: true